INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (48707, -55078, 2, 'Custom - Anti-Magic Shell immunity for Blood Blague');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (48707, -33786, 2, 'Custom - Anti-Magic Shell immunity for Cyclone');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (48707, -51735, 2, 'Custom - Anti-Magic Shell immunity for Ebon Plague');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (48707, -55095, 2, 'Custom - Anti-Magic Shell immunity for Frost Fever');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (48707, -63311, 2, 'Custom - Anti-Magic Shell immunity for Glyph of Shadowflame');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (48707, -51514, 2, 'Custom - Anti-Magic Shell immunity for Hex');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (48707, -50842, 2, 'Custom - Anti-Magic Shell immunity for Pestilience');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (48707, -57981, 2, 'Custom - Anti-Magic Shell immunity for Anesthetic Poison.');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (48707, -3409, 2, 'Custom - Anti-Magic Shell immunity for Crippling Poison.');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (48707, -57970, 2, 'Custom - Anti-Magic Shell immunity for Deadly Poison.');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (48707, -57964, 2, 'Custom - Anti-Magic Shell immunity for Instant Poison.');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (48707, -5760, 2, 'Custom - Anti-Magic Shell immunity for Mind-numbing Poison.');
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `comment`) VALUES (48707, -57975, 2, 'Custom - Anti-Magic Shell immunity for Wound Poison.');
